[package]
name = "media_sorter"
version = "0.1.0"
authors = ["Fredrik Lanker <fredrik@lanker.se>"]
edition = "2018"

[dependencies]
rexiv2 = "0.7.0"
kdtree = "~0.3.1"
quick-csv = "~0.1.6"
rustc-serialize = "~0.3.22"
time = "~0.1.36"
iron = "~0.5.1"
queryst = "~1.0.1"
lazy_static = "~0.2.1"
